"""BoatAdapter protocol — the contract between test steps and the mode-specific harness.

See planning/tdd-architecture.md § C for the full design.
"""
from __future__ import annotations

import pathlib
from typing import Awaitable, Callable, Protocol


class BoatAdapter(Protocol):
    """Abstract interface that every test-harness mode implements.

    Step definitions call this protocol; the harness picks an implementation
    (VirtualAdapter, HilAdapter, LiveIntegrationAdapter) based on --mode.
    """

    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...

    # ---- Stimuli ----
    async def set_bilge(self, wet: bool) -> None: ...
    async def set_shore_power(self, on: bool) -> None: ...
    async def set_generator(self, on: bool) -> None: ...
    async def set_house_voltage(self, volts: float) -> None: ...
    async def set_starter_voltage(self, volts: float) -> None: ...
    async def set_temperature(self, zone: str, celsius: float) -> None: ...
    async def inject_victron(
        self, soc: float, current: float, ttg_min: int
    ) -> None: ...
    async def replay_ais(
        self, path: pathlib.Path, rate: float = 1.0
    ) -> None: ...
    async def set_gps_track(
        self, track: list[tuple[float, float, float]]
    ) -> None: ...

    # ---- Observations (adapter-transparent: HA is always source of truth) ----
    async def entity_state(self, entity_id: str) -> str: ...
    async def wait_for_notification(
        self,
        predicate: Callable[[dict], bool],
        timeout: float,
    ) -> dict: ...
    async def mqtt_last(self, topic: str) -> bytes: ...
